# Generated by Django 5.2.7 on 2026-06-01 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0005_alter_inquiry_contact_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="post_type",
            field=models.CharField(
                choices=[("storage", "보관 중"), ("sighting", "발견 신고")],
                default="storage",
                max_length=20,
            ),
        ),
    ]
