# Generated by Django 5.2.7 on 2026-06-02 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0007_adminrequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="post_type",
            field=models.CharField(
                choices=[("storage", "보관 중"), ("sighting", "분실물 신고")],
                default="storage",
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="AdminRequest",
        ),
    ]
