# Generated by Django 5.2.7 on 2026-06-02 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0008_alter_item_post_type_delete_adminrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="campus",
            field=models.CharField(
                choices=[("jukjeon", "죽전"), ("cheonan", "천안")],
                default="jukjeon",
                max_length=20,
            ),
        ),
    ]
